name: Create Release Build

on:
  release:
    types: [released, prereleased]

jobs:
  check-release:
    name: Release Prefix
    uses: yapsody/actions/.github/workflows/check-release.yml@master
    secrets: inherit
    with:
     release: ${{ github.ref_name }}

  check-history:
    name: Check if release is behind
    needs: check-release
    uses: ks/actions/.github/workflows/check-history.yml@master
    secrets: inherit
    with: 
     release: ${{ github.ref_name }}

  build:
    name: Build
    needs: [ check-release, check-history ]
    if: needs.check-history.outputs.clean && ( needs.check-release.outputs.prefix == 'release' || needs.check-release.outputs.prefix == 'prerelease' )
    uses: ks/actions/.github/workflows/ecr-build-push.yml@master
    secrets: inherit
    with:
      release: "${{ github.ref_name }}"
      cron: true
