AWSTemplateFormatVersion: '2010-09-09'
Description: ECS service setup for running it on a cluster using application load balancer

Parameters:
  EnvironmentName:
    Description: The name of the environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stg
      - prd
    ConstraintDescription: Please choose a valid instance type.

  ServiceName:
    Description: The name of the service to be created
    Type: String
    Default: boilerplate

  ServiceDatabaseName:
      Description: The name of the service database
      Type: String
      Default: boilerplate
  
  ContainerPort:
    Description: What port number the application inside the docker container is binding to
    Type: Number
    Default: 8080

  ContainerCpu:
    Type: Number
    Default: 128
    Description: How much CPU to give the container. 1024 is 1 CPU

  ContainerMemory:
    Type: Number
    Default: 128
    Description: How much memory in megabytes to give the container
  
  RevisionNumber:
    Type: String
    Default: latest
    Description: Git commit slug used as a container tag

  SentryProjectDSN:
    Type: String
    Default: 0
    Description: Sentry project id for error tracking and tracing

# All mappings must be stored here related to environment specific params
# All params must have prefix of the resource followed by the param itself.
Mappings:
  EnvironmentNameToParamsMappings:
    dev:
      LogGroupRetentionInDays: 30
    stg:
      LogGroupRetentionInDays: 30
    prd:
      LogGroupRetentionInDays: 90

Resources:

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'ks-${EnvironmentName}-${ServiceName}'
      RetentionInDays: !FindInMap [EnvironmentNameToParamsMappings, !Ref EnvironmentName, LogGroupRetentionInDays]

  LogGroupCron:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "ks-${EnvironmentName}-${ServiceName}-cron"
      RetentionInDays: !FindInMap [EnvironmentNameToParamsMappings, !Ref EnvironmentName, LogGroupRetentionInDays]


  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: !Sub 'ks-${ServiceName}'
      NamespaceId: 
        Fn::ImportValue: !Sub 'ks-${EnvironmentName}:NamespaceID'
      DnsConfig:
        RoutingPolicy: 'MULTIVALUE'
        DnsRecords:
          - Type: 'SRV'
            TTL: '60'
      HealthCheckCustomConfig:
        FailureThreshold: '1'


  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      UnhealthyThresholdCount: 3
      Name: !Sub 'ks-${EnvironmentName}-${ServiceName}'
      Port: !Ref 'ContainerPort'
      Protocol: TCP
      TargetType: 'instance'
      VpcId:
        Fn::ImportValue:
          !Sub 'ks-${EnvironmentName}:VpcId'
      Tags: 
        - Key: 'project'
          Value: !Sub 'ks-${EnvironmentName}'


  IamRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub 'ks-${EnvironmentName}-${ServiceName}-role'
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - ecs-tasks.amazonaws.com
            Action:
                - 'sts:AssumeRole'
      Description: !Sub "Role for TaskDefinition ${EnvironmentName}-${ServiceName}"
      MaxSessionDuration: 3600
      Path: /
      Tags:
        - Key: project
          Value: !Sub 'ks-${EnvironmentName}'
        - Key: service
          Value: !Sub 'ks-${EnvironmentName}-${ServiceName}'


  IamPolicy:
      Type: "AWS::IAM::Policy"
      Properties:
        PolicyName: !Sub 'ks-${EnvironmentName}-${ServiceName}-policy'
        PolicyDocument: 
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sns:Publish'
              Resource: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${EnvironmentName}-events-topic"
        Roles: 
          - !Ref IamRole


  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Fn::ImportValue: !Sub 'ks-${EnvironmentName}:LoadBalancerARN'
      Protocol: TCP
      Port: !Ref 'ContainerPort'
      DefaultActions:
        - TargetGroupArn: !Ref 'TargetGroup'
          Type: 'forward'
          Order : 1


  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub 'ks-${EnvironmentName}-${ServiceName}'
      RequiresCompatibilities:
        - EC2
      TaskRoleArn: !GetAtt [IamRole, Arn]
      ExecutionRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/ed_ECS_TaskExecutionRole'
      ContainerDefinitions:
        - Name: !Sub 'ks-${EnvironmentName}-${ServiceName}'
          Cpu: !Ref 'ContainerCpu'
          MemoryReservation: !Ref 'ContainerMemory'
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ServiceName}:${RevisionNumber}'
          Privileged: false
          ReadonlyRootFilesystem: true
          User: 'node'
          DockerSecurityOptions:
            - 'apparmor:docker-default'
          DockerLabels:
            com.datadoghq.tags.env: !Sub 'ks-${EnvironmentName}'
            com.datadoghq.tags.service: !Ref 'ServiceName'
            com.datadoghq.tags.version: !Ref 'RevisionNumber'
          EntryPoint: ['sh', '-c', 'export DD_AGENT_HOST=$(cat $ECS_CONTAINER_METADATA_FILE | jq -r .HostPrivateIPv4Address); node ./src/app.js']
          PortMappings:
            - ContainerPort: !Ref 'ContainerPort'
              HostPort: '0'
              Protocol: 'tcp'
          Environment:
            - Name: 'ENVIRONMENT'
              Value: !Sub 'ks-${EnvironmentName}'
            - Name: 'MICROSERVICE_NAME'
              Value: !Ref 'ServiceName'
            - Name: 'MICROSERVICE_TYPE'
              Value: !Sub 'com.yapsody.${ServiceName}'
            - Name: 'APP_PORT'
              Value: !Ref 'ContainerPort'
            - Name: 'MYSQL_DB_NAME'
              Value: !Ref 'ServiceDatabaseName'
            - Name: 'APP_HOST'
              Value: '0.0.0.0'
            - Name: 'DD_ENV'
              Value: !Sub 'ks-${EnvironmentName}'
            - Name: 'DD_SERVICE'
              Value: !Ref 'ServiceName'
            - Name: 'DD_VERSION'
              Value: !Ref 'RevisionNumber'
            - Name: "AWS_REGION"
              Value: !Ref "AWS::Region"
            - Name: "EVENT_SNS_ARN"
              Value: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${EnvironmentName}-events-topic"  
          Secrets:
            - { Name: 'MYSQL_HOST', ValueFrom: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ed_${EnvironmentName}_db_mysql_host' }
            - { Name: "MYSQL_PASSWORD", ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${EnvironmentName}-${ServiceName}-db-user-password" }
            - { Name: "MYSQL_USERNAME", ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${EnvironmentName}-${ServiceName}-db-user" }
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Sub 'ks-${EnvironmentName}-${ServiceName}'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: 'ecs'
        - Name: !Sub "ks-${EnvironmentName}-${ServiceName}-cron"
          Cpu: !Ref "ContainerCpu"
          MemoryReservation: !Ref "ContainerMemory"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ServiceName}-cron:${RevisionNumber}"
          Privileged: false
          DockerSecurityOptions:
            - "apparmor:docker-default"
          DockerLabels:
            com.datadoghq.tags.env: !Sub "ks-${EnvironmentName}"
            com.datadoghq.tags.service: !Sub "${ServiceName}-cron"
            com.datadoghq.tags.version: !Ref "RevisionNumber"
          Environment:
            - Name: "CRON_PORT"
              Value: "443"
          Secrets:
            - { Name: "CRON_HOST", ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ed_${EnvironmentName}_API_HOST" }
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: !Sub "ks-${EnvironmentName}-${ServiceName}-cron"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "ecs"
      Tags: 
       - Key: 'project'
         Value: !Sub 'ks-${EnvironmentName}'
       - Key: 'release'
         Value: !Sub '${RevisionNumber}'
          

  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - ServiceDiscovery
      - TaskDefinition
      - TargetGroup
    Properties:
      ServiceName: !Ref 'ServiceName'
      Cluster: !Sub 'ks-${EnvironmentName}-cluster'
      LaunchType: 'EC2'
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: '1'
      TaskDefinition: !Ref 'TaskDefinition'
      PropagateTags: TASK_DEFINITION
      LoadBalancers:
        - ContainerName: !Sub 'ks-${EnvironmentName}-${ServiceName}'
          ContainerPort: !Ref 'ContainerPort'
          TargetGroupArn: !Ref 'TargetGroup'
      ServiceRegistries:
        - RegistryArn: !GetAtt 'ServiceDiscovery.Arn'
          ContainerName: !Sub 'ks-${EnvironmentName}-${ServiceName}'
          ContainerPort: !Ref 'ContainerPort'
      #Tags: 
      #  - Key: 'project'
      #    Value: !Sub 'ks-${EnvironmentName}'
