name: Deploy Release

run-name: Deploy release ${{ inputs.release }} to ${{ inputs.deploy-environment }} environment

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release to Deploy'
        required: true
        type: string
      deploy-environment:
        description: 'Deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - 'dev'
          - 'stg'
          - 'prd'
      project:
        description: 'Project'
        required: true
        default: 'ed'
        type: choice
        options:
          - 'ks'
          - 'ks-tp'

jobs:

  check-release:
    name: Release Prefix
    uses: ks/actions/.github/workflows/check-release-deploy.yml@master
    secrets: inherit
    with: 
     release: ${{ inputs.release }}

  check-build:
    name: Check if Build exists
    needs: check-release
    uses: ks/actions/.github/workflows/check-build-ed.yml@master
    secrets: inherit
    with:
      deploy-environment: ${{ inputs.deploy-environment }}
      release: ${{ inputs.release }}

  deploy-service:
    needs: [ check-release, check-build ]
    if: needs.check-build.outputs.build_present && (( needs.check-release.outputs.prefix == 'release' && inputs.deploy-environment == 'prd') || ( needs.check-release.outputs.prefix == 'prerelease' && inputs.deploy-environment != 'prd'))
    uses: ks/actions/.github/workflows/deploy-service.yml@master
    secrets: inherit
    with:
      deploy-environment: ${{ inputs.deploy-environment }}
      release: ${{ inputs.release }}
      project: ${{ inputs.project }}
